/**
 * Semantic Learning Bridge
 *
 * Connects the Pattern Recognizer, Preference Model, and Decision Queue
 * to enable cross-system learning and adaptive behavior improvement.
 *
 * This module serves as the "feedback loop" for the Cognitive Synthesis Engine:
 *
 * 1. Pattern Detection → Preference Rules
 *    When PatternRecognizer detects recurring patterns, convert them to
 *    preference model rules (urgency triggers, auto-archive patterns)
 *
 * 2. Decision Resolution → Correction Learning
 *    When a decision is resolved, feed it back to the Preference Model
 *    as a learning signal (similar to recordCorrection)
 *
 * 3. Preference Insights → Pattern Guidance
 *    Use preference model knowledge to guide pattern detection
 *
 * SECURITY: This module must ONLY be imported in server-side code.
 */

import { ensureServerOnly } from '../server-only-guard';
import { getPatternRecognizer, type RecurringPattern, type PatternMatch } from './pattern-recognizer';
import {
  loadPreferences,
  savePreferences,
  recordCorrection,
  type JamesPreferenceModel,
  type PatternRule,
  type UrgencyLevel,
  type Domain,
} from '../ea/preference-model';
import {
  getDecisionQueue,
  type PendingDecision,
  type DecisionOption,
  type DecisionReason,
} from '../cortex/decision-queue';
import { getEventBus, createNotificationEvent, DOMAINS } from '../agents/life-os-event-bus';
import {
  getRuleLifecycleManager,
  type ContradictionReport,
  type RuleWithProvenance,
  type RuleCategory,
} from './rule-lifecycle';

ensureServerOnly('lib/learning/semantic-learning-bridge');

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * Learning insight generated by the bridge
 */
export interface LearningInsight {
  id: string;
  type: 'pattern_to_rule' | 'decision_to_correction' | 'preference_update' | 'contradiction_detected' | 'contradiction_resolved' | 'rule_decayed' | 'rule_reinforced';
  source: 'pattern_recognizer' | 'decision_queue' | 'preference_model' | 'rule_lifecycle';
  target: 'preference_model' | 'pattern_recognizer' | 'synthesis_loop' | 'rule_lifecycle';
  description: string;
  timestamp: string;
  applied: boolean;
  metadata?: Record<string, unknown>;
}

/**
 * Bridge configuration
 */
export interface SemanticLearningConfig {
  // Minimum pattern confidence to convert to preference rule
  patternToRuleThreshold: number;

  // Minimum pattern frequency (per week) to consider for rule conversion
  minPatternFrequency: number;

  // Enable automatic rule creation from patterns
  autoCreateRules: boolean;

  // Enable decision resolution learning
  learnFromDecisions: boolean;

  // Maximum rules to create per learning cycle
  maxRulesPerCycle: number;

  // Enable contradiction detection during learning cycles
  detectContradictions: boolean;

  // Auto-resolve low-severity contradictions
  autoResolveContradictions: boolean;

  // Enable confidence decay for stale rules
  enableDecay: boolean;

  // Days without reinforcement before decay starts
  decayGracePeriodDays: number;
}

const DEFAULT_CONFIG: SemanticLearningConfig = {
  patternToRuleThreshold: 0.7,
  minPatternFrequency: 3,
  autoCreateRules: true,
  learnFromDecisions: true,
  maxRulesPerCycle: 5,
  detectContradictions: true,
  autoResolveContradictions: true,
  enableDecay: true,
  decayGracePeriodDays: 30,
};

// ============================================================================
// Pattern to Preference Rule Conversion
// ============================================================================

/**
 * Convert a detected pattern into a preference model rule
 */
function patternToPreferenceRule(pattern: RecurringPattern): PatternRule | null {
  // Skip patterns with low confidence
  if (pattern.confidence < 0.5) {
    return null;
  }

  // Extract keywords from pattern description and examples
  const keywords = extractKeywordsFromPattern(pattern);
  if (keywords.length === 0) {
    return null;
  }

  const rule: PatternRule = {
    pattern: keywords.join('|'),
    isRegex: true,
    caseSensitive: false,
    weight: Math.min(0.9, pattern.confidence),
    learnedAt: new Date().toISOString(),
    source: 'inferred',
    exampleMatches: pattern.examples.slice(0, 3),
  };

  return rule;
}

/**
 * Extract meaningful keywords from a pattern
 */
function extractKeywordsFromPattern(pattern: RecurringPattern): string[] {
  const keywords: string[] = [];

  // Extract from description
  const descWords = pattern.description
    .toLowerCase()
    .replace(/[^\w\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 4);

  keywords.push(...descWords.slice(0, 3));

  // Extract from examples
  for (const example of pattern.examples) {
    try {
      const parsed = JSON.parse(example);
      if (typeof parsed === 'object') {
        // Extract from subject, title, or content fields
        const text = [parsed.subject, parsed.title, parsed.content]
          .filter(Boolean)
          .join(' ')
          .toLowerCase();

        const words = text
          .replace(/[^\w\s]/g, ' ')
          .split(/\s+/)
          .filter((w) => w.length > 4);

        keywords.push(...words.slice(0, 2));
      }
    } catch {
      // Not JSON, extract directly
      const words = example
        .toLowerCase()
        .replace(/[^\w\s]/g, ' ')
        .split(/\s+/)
        .filter((w) => w.length > 4);

      keywords.push(...words.slice(0, 2));
    }
  }

  // Deduplicate and limit
  return Array.from(new Set(keywords)).slice(0, 5);
}

/**
 * Determine if a pattern should become an urgency trigger or archive pattern
 */
function categorizePattern(pattern: RecurringPattern): 'urgency' | 'archive' | 'skip' {
  const descLower = pattern.description.toLowerCase();

  // Check if this is about escalation or high-priority items
  if (
    descLower.includes('escalat') ||
    descLower.includes('critical') ||
    descLower.includes('urgent') ||
    descLower.includes('high') ||
    pattern.type === 'escalation'
  ) {
    return 'urgency';
  }

  // Check if this is about low-priority or dismissable items
  if (
    descLower.includes('archive') ||
    descLower.includes('dismiss') ||
    descLower.includes('low') ||
    descLower.includes('newsletter') ||
    descLower.includes('promotional')
  ) {
    return 'archive';
  }

  // Default: skip patterns that don't clearly fit
  return 'skip';
}

// ============================================================================
// Decision Resolution Learning
// ============================================================================

/**
 * Learn from a resolved decision
 *
 * When a human resolves a NEEDS_DECISION item, we can learn:
 * - Which option they chose (and why)
 * - Whether the LLM's recommendation was correct
 * - Patterns in the decision context
 */
async function learnFromDecisionResolution(
  decision: PendingDecision,
  preferences: JamesPreferenceModel
): Promise<LearningInsight | null> {
  if (decision.status !== 'resolved' || !decision.selectedOptionId) {
    return null;
  }

  const selectedOption = decision.options.find((o) => o.id === decision.selectedOptionId);
  const recommendedOption = decision.options.find((o) => o.recommended);

  if (!selectedOption) {
    return null;
  }

  // If user chose the recommended option, this validates the LLM's reasoning
  // If not, this is a learning opportunity

  const wasRecommendedChosen = recommendedOption?.id === selectedOption.id;

  if (wasRecommendedChosen) {
    // Reinforce the LLM's decision-making - could boost pattern confidence
    console.log(`[SemanticBridge] Decision ${decision.id}: User confirmed LLM recommendation`);

    return {
      id: `insight_${Date.now()}`,
      type: 'decision_to_correction',
      source: 'decision_queue',
      target: 'preference_model',
      description: `User confirmed recommended option "${selectedOption.label}" - positive reinforcement`,
      timestamp: new Date().toISOString(),
      applied: true,
      metadata: {
        decisionId: decision.id,
        optionChosen: selectedOption.label,
        wasRecommended: true,
        domain: decision.domain,
      },
    };
  }

  // User chose a different option - this is a correction
  console.log(
    `[SemanticBridge] Decision ${decision.id}: User chose "${selectedOption.label}" over recommended "${recommendedOption?.label}"`
  );

  // Record this as a correction in the preference model
  try {
    await recordCorrection(
      decision.id,
      {
        urgency: mapPriorityToUrgency(decision.priority),
        domain: (decision.domain as Domain) || 'general',
        action: recommendedOption?.action || 'unknown',
      },
      {
        urgency: inferUrgencyFromOption(selectedOption),
        domain: (decision.domain as Domain) || 'general',
        action: selectedOption.action,
      },
      decision.userFeedback || `User chose "${selectedOption.label}" instead of recommended option`,
      {
        type: 'notification',
        summary: decision.title,
        content: decision.context,
      }
    );

    return {
      id: `insight_${Date.now()}`,
      type: 'decision_to_correction',
      source: 'decision_queue',
      target: 'preference_model',
      description: `Recorded correction: "${selectedOption.label}" chosen over "${recommendedOption?.label}"`,
      timestamp: new Date().toISOString(),
      applied: true,
      metadata: {
        decisionId: decision.id,
        optionChosen: selectedOption.label,
        recommendedOption: recommendedOption?.label,
        reason: decision.userFeedback,
        domain: decision.domain,
      },
    };
  } catch (error) {
    console.error('[SemanticBridge] Error recording correction:', error);
    return null;
  }
}

/**
 * Map decision priority to urgency level
 */
function mapPriorityToUrgency(priority: 'critical' | 'high' | 'medium' | 'low'): UrgencyLevel {
  switch (priority) {
    case 'critical':
      return 'critical';
    case 'high':
      return 'high';
    case 'medium':
      return 'medium';
    case 'low':
      return 'low';
    default:
      return 'medium';
  }
}

/**
 * Infer urgency level from the chosen option
 */
function inferUrgencyFromOption(option: DecisionOption): UrgencyLevel {
  const actionLower = option.action.toLowerCase();

  if (actionLower.includes('escalate') || actionLower.includes('urgent')) {
    return 'critical';
  }
  if (actionLower.includes('high') || actionLower.includes('priorit')) {
    return 'high';
  }
  if (actionLower.includes('archive') || actionLower.includes('dismiss')) {
    return 'background';
  }
  if (actionLower.includes('defer') || actionLower.includes('later')) {
    return 'low';
  }

  return 'medium';
}

// ============================================================================
// Main Bridge Class
// ============================================================================

/**
 * Semantic Learning Bridge
 *
 * Orchestrates cross-system learning between Pattern Recognizer,
 * Preference Model, and Decision Queue.
 */
export class SemanticLearningBridge {
  private config: SemanticLearningConfig;
  private insights: LearningInsight[] = [];
  private lastLearningCycle: number = 0;

  constructor(config?: Partial<SemanticLearningConfig>) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    console.log('[SemanticBridge] Initialized with config:', this.config);
  }

  /**
   * Run a learning cycle
   *
   * This is the main entry point that should be called periodically
   * (e.g., every 30 minutes or after significant activity).
   */
  async runLearningCycle(): Promise<LearningInsight[]> {
    const startTime = Date.now();
    const cycleInsights: LearningInsight[] = [];

    console.log('[SemanticBridge] Starting learning cycle...');

    try {
      // 1. Load current preferences
      const preferences = await loadPreferences();

      // 2. Process detected patterns
      if (this.config.autoCreateRules) {
        const patternInsights = await this.processPatterns(preferences);
        cycleInsights.push(...patternInsights);
      }

      // 3. Process resolved decisions
      if (this.config.learnFromDecisions) {
        const decisionInsights = await this.processResolvedDecisions(preferences);
        cycleInsights.push(...decisionInsights);
      }

      // 4. Process contradiction detection
      if (this.config.detectContradictions) {
        const contradictionInsights = await this.processContradictions(preferences);
        cycleInsights.push(...contradictionInsights);
      }

      // 5. Process confidence decay for stale rules
      if (this.config.enableDecay) {
        const decayInsights = await this.processDecay(preferences);
        cycleInsights.push(...decayInsights);
      }

      // 6. Save updated preferences if any insights were applied
      const appliedCount = cycleInsights.filter((i) => i.applied).length;
      if (appliedCount > 0) {
        await savePreferences(preferences);
        console.log(`[SemanticBridge] Saved preferences with ${appliedCount} updates`);
      }

      // 7. Track insights
      this.insights.push(...cycleInsights);
      this.lastLearningCycle = Date.now();

      // 8. Publish learning cycle complete event
      if (cycleInsights.length > 0) {
        const eventBus = getEventBus();
        await eventBus.publish(
          createNotificationEvent(
            'semantic-learning-bridge',
            {
              type: 'learning-cycle-complete',
              insightsGenerated: cycleInsights.length,
              insightsApplied: appliedCount,
              durationMs: Date.now() - startTime,
            },
            DOMAINS.LEARNING,
            'low'
          )
        );
      }

      console.log(
        `[SemanticBridge] Learning cycle complete: ${cycleInsights.length} insights (${Date.now() - startTime}ms)`
      );

      return cycleInsights;
    } catch (error) {
      console.error('[SemanticBridge] Learning cycle failed:', error);
      return [];
    }
  }

  /**
   * Process detected patterns and convert to preference rules
   */
  private async processPatterns(preferences: JamesPreferenceModel): Promise<LearningInsight[]> {
    const insights: LearningInsight[] = [];
    const patternRecognizer = getPatternRecognizer();
    const patterns = patternRecognizer.getAllPatterns();

    let rulesCreated = 0;

    for (const pattern of patterns) {
      // Skip if we've created enough rules this cycle
      if (rulesCreated >= this.config.maxRulesPerCycle) {
        break;
      }

      // Check if pattern meets thresholds
      if (
        pattern.confidence < this.config.patternToRuleThreshold ||
        pattern.frequency < this.config.minPatternFrequency
      ) {
        continue;
      }

      // Determine what kind of rule this should be
      const category = categorizePattern(pattern);
      if (category === 'skip') {
        continue;
      }

      // Convert pattern to rule
      const rule = patternToPreferenceRule(pattern);
      if (!rule) {
        continue;
      }

      // Check if similar rule already exists
      const targetList =
        category === 'urgency' ? preferences.urgency_triggers : preferences.auto_archive_patterns;

      const alreadyExists = targetList.some(
        (existing) =>
          existing.pattern.toLowerCase().includes(rule.pattern.toLowerCase()) ||
          rule.pattern.toLowerCase().includes(existing.pattern.toLowerCase())
      );

      if (alreadyExists) {
        continue;
      }

      // Add the new rule to preference model
      targetList.push(rule);
      rulesCreated++;

      // Register rule with RuleLifecycleManager for provenance tracking
      let ruleId: string | undefined;
      try {
        const lifecycleManager = getRuleLifecycleManager();
        const ruleCategory: RuleCategory = category === 'urgency' ? 'urgency_trigger' : 'auto_archive';

        // Extract event IDs from pattern metadata if available
        const derivedFromEvents: string[] = [];
        const patternMetadata = pattern.metadata as Record<string, unknown> | undefined;
        if (patternMetadata?.lastMatchedEventId) {
          derivedFromEvents.push(String(patternMetadata.lastMatchedEventId));
        }
        if (patternMetadata?.sourceEventIds && Array.isArray(patternMetadata.sourceEventIds)) {
          derivedFromEvents.push(...patternMetadata.sourceEventIds.map(String));
        }

        ruleId = await lifecycleManager.addRule(rule, ruleCategory, derivedFromEvents);
        console.log(`[SemanticBridge] Registered rule ${ruleId} in provenance system`);
      } catch (error) {
        console.error('[SemanticBridge] Failed to register rule with lifecycle manager:', error);
      }

      insights.push({
        id: `insight_pattern_${pattern.id}`,
        type: 'pattern_to_rule',
        source: 'pattern_recognizer',
        target: 'preference_model',
        description: `Created ${category} rule from pattern: "${rule.pattern}"`,
        timestamp: new Date().toISOString(),
        applied: true,
        metadata: {
          patternId: pattern.id,
          patternType: pattern.type,
          confidence: pattern.confidence,
          frequency: pattern.frequency,
          ruleCategory: category,
          ruleId, // Include provenance ID for tracking
        },
      });

      console.log(`[SemanticBridge] Created ${category} rule: "${rule.pattern}"`);
    }

    return insights;
  }

  /**
   * Process resolved decisions and learn from them
   */
  private async processResolvedDecisions(
    preferences: JamesPreferenceModel
  ): Promise<LearningInsight[]> {
    const insights: LearningInsight[] = [];
    const decisionQueue = getDecisionQueue();

    // Get recently resolved decisions (last 24 hours)
    const allDecisions = await decisionQueue.getPendingDecisions({ status: 'resolved' });

    const recentCutoff = Date.now() - 24 * 60 * 60 * 1000;
    const recentDecisions = allDecisions.filter(
      (d) => d.resolvedAt && new Date(d.resolvedAt).getTime() > recentCutoff
    );

    for (const decision of recentDecisions) {
      const insight = await learnFromDecisionResolution(decision, preferences);
      if (insight) {
        insights.push(insight);
      }
    }

    return insights;
  }

  /**
   * Process contradiction detection between rules
   *
   * Finds conflicting preference rules and either auto-resolves them
   * or creates insights for human review.
   *
   * Note: The RuleLifecycleManager maintains its own provenance database,
   * so contradiction detection works on tracked rules, not the raw preference arrays.
   */
  private async processContradictions(
    _preferences: JamesPreferenceModel
  ): Promise<LearningInsight[]> {
    const insights: LearningInsight[] = [];

    try {
      const lifecycleManager = getRuleLifecycleManager();

      // Detect contradictions across all tracked rules
      const contradictions = await lifecycleManager.detectContradictions();

      for (const contradiction of contradictions) {
        // Create insight for detected contradiction
        insights.push({
          id: `insight_contradiction_${contradiction.id}`,
          type: 'contradiction_detected',
          source: 'rule_lifecycle',
          target: 'preference_model',
          description: `Contradiction detected: Rule "${contradiction.rule1Id}" conflicts with "${contradiction.rule2Id}" - ${contradiction.description}`,
          timestamp: new Date().toISOString(),
          applied: false,
          metadata: {
            contradictionId: contradiction.id,
            type: contradiction.contradictionType,
            severity: contradiction.severity,
            rule1Id: contradiction.rule1Id,
            rule2Id: contradiction.rule2Id,
            suggestedResolution: contradiction.suggestedResolution,
          },
        });

        // Auto-resolve low severity contradictions
        if (this.config.autoResolveContradictions && contradiction.severity === 'low') {
          // Use suggested resolution or default to merge for low severity
          const resolution = contradiction.suggestedResolution === 'human_review'
            ? 'merge' as const
            : contradiction.suggestedResolution === 'keep_rule1'
              ? 'keep_rule1' as const
              : contradiction.suggestedResolution === 'keep_rule2'
                ? 'keep_rule2' as const
                : 'merge' as const;

          await lifecycleManager.resolveContradiction(contradiction.id, resolution);

          insights.push({
            id: `insight_contradiction_resolved_${contradiction.id}`,
            type: 'contradiction_resolved',
            source: 'rule_lifecycle',
            target: 'preference_model',
            description: `Auto-resolved low-severity contradiction: ${resolution}`,
            timestamp: new Date().toISOString(),
            applied: true,
            metadata: {
              contradictionId: contradiction.id,
              resolution,
              automatic: true,
            },
          });
        }
      }

      if (contradictions.length > 0) {
        console.log(
          `[SemanticBridge] Found ${contradictions.length} contradictions, auto-resolved ${
            insights.filter((i) => i.type === 'contradiction_resolved').length
          }`
        );
      }
    } catch (error) {
      console.error('[SemanticBridge] Error processing contradictions:', error);
    }

    return insights;
  }

  /**
   * Process confidence decay for stale rules
   *
   * Rules that haven't been reinforced recently lose confidence weight.
   * This ensures that old patterns don't dominate over newer behavior.
   *
   * The RuleLifecycleManager handles decay through its own provenance tracking.
   * This method runs the decay cycle and creates insights based on results.
   */
  private async processDecay(
    _preferences: JamesPreferenceModel
  ): Promise<LearningInsight[]> {
    const insights: LearningInsight[] = [];

    try {
      const lifecycleManager = getRuleLifecycleManager();

      // Run the decay cycle - this checks all tracked rules
      const decayResult = await lifecycleManager.runDecayCycle();

      // Create insights for decayed rules
      for (const ruleId of decayResult.decayed) {
        insights.push({
          id: `insight_decay_${Date.now()}_${ruleId}`,
          type: 'rule_decayed',
          source: 'rule_lifecycle',
          target: 'preference_model',
          description: `Rule ${ruleId} had confidence reduced due to lack of reinforcement`,
          timestamp: new Date().toISOString(),
          applied: true,
          metadata: {
            ruleId,
            action: 'decayed',
          },
        });
      }

      // Create insights for archived rules (decayed below threshold)
      for (const ruleId of decayResult.archived) {
        insights.push({
          id: `insight_archived_${Date.now()}_${ruleId}`,
          type: 'rule_decayed',
          source: 'rule_lifecycle',
          target: 'preference_model',
          description: `Rule ${ruleId} was archived after decaying below minimum confidence threshold`,
          timestamp: new Date().toISOString(),
          applied: true,
          metadata: {
            ruleId,
            action: 'archived',
          },
        });
      }

      if (decayResult.decayed.length > 0 || decayResult.archived.length > 0) {
        console.log(
          `[SemanticBridge] Decay cycle: ${decayResult.decayed.length} decayed, ${decayResult.archived.length} archived`
        );
      }
    } catch (error) {
      console.error('[SemanticBridge] Error processing decay:', error);
    }

    return insights;
  }

  /**
   * Reinforce a rule when it matches user behavior
   *
   * Call this when a rule successfully predicts user action.
   * @param ruleId - The rule ID from the provenance system
   * @param eventIds - Optional event IDs that triggered this reinforcement
   */
  async reinforceRule(ruleId: string, eventIds: string[] = []): Promise<void> {
    try {
      const lifecycleManager = getRuleLifecycleManager();
      await lifecycleManager.reinforceRule(ruleId, eventIds);

      console.log(`[SemanticBridge] Reinforced rule: ${ruleId}`);
    } catch (error) {
      console.error('[SemanticBridge] Error reinforcing rule:', error);
    }
  }

  /**
   * Get learning statistics
   */
  getStats(): {
    totalInsights: number;
    appliedInsights: number;
    lastLearningCycle: number | null;
    insightsByType: Record<string, number>;
    insightsBySource: Record<string, number>;
  } {
    const byType: Record<string, number> = {};
    const bySource: Record<string, number> = {};

    for (const insight of this.insights) {
      byType[insight.type] = (byType[insight.type] || 0) + 1;
      bySource[insight.source] = (bySource[insight.source] || 0) + 1;
    }

    return {
      totalInsights: this.insights.length,
      appliedInsights: this.insights.filter((i) => i.applied).length,
      lastLearningCycle: this.lastLearningCycle || null,
      insightsByType: byType,
      insightsBySource: bySource,
    };
  }

  /**
   * Get recent insights
   */
  getRecentInsights(limit: number = 20): LearningInsight[] {
    return this.insights.slice(-limit);
  }

  /**
   * Clear insight history
   */
  clearInsights(): void {
    this.insights = [];
    console.log('[SemanticBridge] Cleared insight history');
  }
}

// ============================================================================
// Singleton Instance
// ============================================================================

let instance: SemanticLearningBridge | null = null;

export function getSemanticLearningBridge(
  config?: Partial<SemanticLearningConfig>
): SemanticLearningBridge {
  if (!instance) {
    instance = new SemanticLearningBridge(config);
  }
  return instance;
}

/**
 * Reset singleton instance (useful for testing)
 */
export function resetSemanticLearningBridge(): void {
  instance = null;
}

// ============================================================================
// Helper Functions for External Use
// ============================================================================

/**
 * Trigger a learning cycle from external systems
 */
export async function triggerLearningCycle(): Promise<LearningInsight[]> {
  const bridge = getSemanticLearningBridge();
  return bridge.runLearningCycle();
}

/**
 * Get patterns that match an event for enhanced classification
 */
export function findPatternsForEvent(event: {
  type: string;
  domain?: string;
  source: string;
  timestamp: Date;
  payload?: unknown;
}): PatternMatch[] {
  const patternRecognizer = getPatternRecognizer();
  return patternRecognizer.findMatchingPatterns({
    id: `temp_${Date.now()}`,
    type: event.type as 'message' | 'task' | 'notification' | 'escalation',
    domain: event.domain,
    source: event.source,
    timestamp: event.timestamp,
    payload: event.payload,
    priority: 'normal',
  });
}

/**
 * Migrate existing preference model rules to the lifecycle tracking system.
 *
 * This is a one-time operation that imports all existing urgency triggers
 * and auto-archive patterns into the RuleLifecycleManager for provenance
 * tracking, decay management, and contradiction detection.
 *
 * Call this when:
 * - First setting up provenance tracking on an existing system
 * - After loading preferences that might have rules not in the lifecycle system
 */
export async function migrateRulesToLifecycleSystem(): Promise<{
  imported: number;
  skipped: number;
  errors: string[];
}> {
  const preferences = await loadPreferences();
  const lifecycleManager = getRuleLifecycleManager();
  const errors: string[] = [];
  let imported = 0;
  let skipped = 0;

  console.log('[SemanticBridge] Starting migration of preference rules to lifecycle system...');

  // Import urgency triggers
  for (const rule of preferences.urgency_triggers) {
    try {
      await lifecycleManager.addRule(rule, 'urgency_trigger', []);
      imported++;
    } catch (error) {
      // Skip if already exists (duplicate key error)
      if (error instanceof Error && error.message.includes('UNIQUE constraint')) {
        skipped++;
      } else {
        errors.push(`Urgency trigger "${rule.pattern}": ${error}`);
      }
    }
  }

  // Import auto-archive patterns
  for (const rule of preferences.auto_archive_patterns) {
    try {
      await lifecycleManager.addRule(rule, 'auto_archive', []);
      imported++;
    } catch (error) {
      // Skip if already exists
      if (error instanceof Error && error.message.includes('UNIQUE constraint')) {
        skipped++;
      } else {
        errors.push(`Auto-archive pattern "${rule.pattern}": ${error}`);
      }
    }
  }

  console.log(
    `[SemanticBridge] Migration complete: ${imported} imported, ${skipped} skipped (already exists), ${errors.length} errors`
  );

  return { imported, skipped, errors };
}

/**
 * Sync lifecycle system state back to preference model.
 *
 * This ensures the preference model only contains active rules from
 * the lifecycle system, removing any that have been archived or
 * decayed below threshold.
 *
 * Call this after running decay cycles or resolving contradictions.
 */
export async function syncLifecycleToPreferences(): Promise<{
  urgencyTriggers: number;
  autoArchivePatterns: number;
  removed: number;
}> {
  const preferences = await loadPreferences();
  const lifecycleManager = getRuleLifecycleManager();
  const activeRules = await lifecycleManager.getActiveRules();

  const originalUrgencyCount = preferences.urgency_triggers.length;
  const originalArchiveCount = preferences.auto_archive_patterns.length;

  // Build lookup of active rules by pattern
  const activeUrgencyPatterns = new Set(
    activeRules
      .filter((r) => r.category === 'urgency_trigger')
      .map((r) => r.rule.pattern.toLowerCase())
  );

  const activeArchivePatterns = new Set(
    activeRules
      .filter((r) => r.category === 'auto_archive')
      .map((r) => r.rule.pattern.toLowerCase())
  );

  // Filter preference model to only active rules
  preferences.urgency_triggers = preferences.urgency_triggers.filter((rule) =>
    activeUrgencyPatterns.has(rule.pattern.toLowerCase())
  );

  preferences.auto_archive_patterns = preferences.auto_archive_patterns.filter((rule) =>
    activeArchivePatterns.has(rule.pattern.toLowerCase())
  );

  const removed =
    originalUrgencyCount -
    preferences.urgency_triggers.length +
    originalArchiveCount -
    preferences.auto_archive_patterns.length;

  if (removed > 0) {
    await savePreferences(preferences);
    console.log(
      `[SemanticBridge] Synced preferences: removed ${removed} inactive rules`
    );
  }

  return {
    urgencyTriggers: preferences.urgency_triggers.length,
    autoArchivePatterns: preferences.auto_archive_patterns.length,
    removed,
  };
}
