-- HYRO FORGE: Mathematics Curriculum
-- Migration 020: Common Core Grade 6 Math + Extensions through Grade 8
-- Utah Core Standards alignment with advanced extensions
-- Goal: Common Core as FLOOR, mastery FAR beyond state testing

-- ============================================================================
-- GRADE 6 MATHEMATICS STANDARDS (Common Core)
-- ============================================================================

-- 6.RP - Ratios and Proportional Relationships
INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed) VALUES
  ('math_6rp_a1', 'mathematics', 'common_core', '6.RP.A.1', 'Understand Ratio Concepts', 'Understand the concept of a ratio and use ratio language to describe a ratio relationship between two quantities.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 1, 1),
  ('math_6rp_a2', 'mathematics', 'common_core', '6.RP.A.2', 'Unit Rates', 'Understand the concept of a unit rate a/b associated with a ratio a:b with b ≠ 0, and use rate language in the context of a ratio relationship.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 2, 1),
  ('math_6rp_a3', 'mathematics', 'common_core', '6.RP.A.3', 'Use Ratios to Solve Problems', 'Use ratio and rate reasoning to solve real-world and mathematical problems.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 3, 1),
  ('math_6rp_a3a', 'mathematics', 'common_core', '6.RP.A.3a', 'Equivalent Ratios Tables', 'Make tables of equivalent ratios relating quantities with whole-number measurements.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 4, 1),
  ('math_6rp_a3b', 'mathematics', 'common_core', '6.RP.A.3b', 'Unit Rate Problems', 'Solve unit rate problems including those involving unit pricing and constant speed.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 5, 1),
  ('math_6rp_a3c', 'mathematics', 'common_core', '6.RP.A.3c', 'Percent Problems', 'Find a percent of a quantity as a rate per 100; solve problems involving finding the whole, given a part and the percent.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 6, 1),
  ('math_6rp_a3d', 'mathematics', 'common_core', '6.RP.A.3d', 'Ratio Reasoning with Conversions', 'Use ratio reasoning to convert measurement units; manipulate and transform units appropriately when multiplying or dividing quantities.', 6, 'middle', 'Ratios & Proportions', 'Understand ratio concepts', 7, 1);

-- 6.NS - The Number System
INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed) VALUES
  ('math_6ns_a1', 'mathematics', 'common_core', '6.NS.A.1', 'Divide Fractions', 'Interpret and compute quotients of fractions, and solve word problems involving division of fractions by fractions.', 6, 'middle', 'Number System', 'Apply and extend previous understandings of multiplication and division', 10, 1),
  ('math_6ns_b2', 'mathematics', 'common_core', '6.NS.B.2', 'Multi-digit Division', 'Fluently divide multi-digit numbers using the standard algorithm.', 6, 'middle', 'Number System', 'Compute fluently with multi-digit numbers', 11, 1),
  ('math_6ns_b3', 'mathematics', 'common_core', '6.NS.B.3', 'Multi-digit Decimal Operations', 'Fluently add, subtract, multiply, and divide multi-digit decimals using the standard algorithm for each operation.', 6, 'middle', 'Number System', 'Compute fluently with multi-digit numbers', 12, 1),
  ('math_6ns_b4', 'mathematics', 'common_core', '6.NS.B.4', 'GCF and LCM', 'Find the greatest common factor of two whole numbers less than or equal to 100 and the least common multiple of two whole numbers less than or equal to 12.', 6, 'middle', 'Number System', 'Compute fluently with multi-digit numbers', 13, 1),
  ('math_6ns_c5', 'mathematics', 'common_core', '6.NS.C.5', 'Understand Positive and Negative Numbers', 'Understand that positive and negative numbers are used together to describe quantities having opposite directions or values.', 6, 'middle', 'Number System', 'Apply and extend previous understandings of numbers to the system of rational numbers', 14, 1),
  ('math_6ns_c6', 'mathematics', 'common_core', '6.NS.C.6', 'Rational Numbers on Number Line', 'Understand a rational number as a point on the number line. Extend number line diagrams and coordinate axes.', 6, 'middle', 'Number System', 'Apply and extend previous understandings of numbers to the system of rational numbers', 15, 1),
  ('math_6ns_c7', 'mathematics', 'common_core', '6.NS.C.7', 'Order and Absolute Value', 'Understand ordering and absolute value of rational numbers.', 6, 'middle', 'Number System', 'Apply and extend previous understandings of numbers to the system of rational numbers', 16, 1),
  ('math_6ns_c8', 'mathematics', 'common_core', '6.NS.C.8', 'Coordinate Plane Problems', 'Solve real-world and mathematical problems by graphing points in all four quadrants of the coordinate plane.', 6, 'middle', 'Number System', 'Apply and extend previous understandings of numbers to the system of rational numbers', 17, 1);

-- 6.EE - Expressions and Equations
INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed) VALUES
  ('math_6ee_a1', 'mathematics', 'common_core', '6.EE.A.1', 'Exponents', 'Write and evaluate numerical expressions involving whole-number exponents.', 6, 'middle', 'Expressions & Equations', 'Apply and extend previous understandings of arithmetic to algebraic expressions', 20, 1),
  ('math_6ee_a2', 'mathematics', 'common_core', '6.EE.A.2', 'Read and Write Expressions', 'Write, read, and evaluate expressions in which letters stand for numbers.', 6, 'middle', 'Expressions & Equations', 'Apply and extend previous understandings of arithmetic to algebraic expressions', 21, 1),
  ('math_6ee_a3', 'mathematics', 'common_core', '6.EE.A.3', 'Equivalent Expressions', 'Apply the properties of operations to generate equivalent expressions.', 6, 'middle', 'Expressions & Equations', 'Apply and extend previous understandings of arithmetic to algebraic expressions', 22, 1),
  ('math_6ee_a4', 'mathematics', 'common_core', '6.EE.A.4', 'Identify Equivalent Expressions', 'Identify when two expressions are equivalent (i.e., when the two expressions name the same number regardless of which value is substituted into them).', 6, 'middle', 'Expressions & Equations', 'Apply and extend previous understandings of arithmetic to algebraic expressions', 23, 1),
  ('math_6ee_b5', 'mathematics', 'common_core', '6.EE.B.5', 'Solve Equations as Process', 'Understand solving an equation or inequality as a process of answering a question: which values from a specified set, if any, make the equation or inequality true?', 6, 'middle', 'Expressions & Equations', 'Reason about and solve one-variable equations and inequalities', 24, 1),
  ('math_6ee_b6', 'mathematics', 'common_core', '6.EE.B.6', 'Variables for Unknown Numbers', 'Use variables to represent numbers and write expressions when solving a real-world or mathematical problem.', 6, 'middle', 'Expressions & Equations', 'Reason about and solve one-variable equations and inequalities', 25, 1),
  ('math_6ee_b7', 'mathematics', 'common_core', '6.EE.B.7', 'Solve Real-World Equations', 'Solve real-world and mathematical problems by writing and solving equations of the form x + p = q and px = q for cases in which p, q and x are all nonnegative rational numbers.', 6, 'middle', 'Expressions & Equations', 'Reason about and solve one-variable equations and inequalities', 26, 1),
  ('math_6ee_b8', 'mathematics', 'common_core', '6.EE.B.8', 'Inequalities', 'Write an inequality of the form x > c or x < c to represent a constraint or condition in a real-world or mathematical problem.', 6, 'middle', 'Expressions & Equations', 'Reason about and solve one-variable equations and inequalities', 27, 1),
  ('math_6ee_c9', 'mathematics', 'common_core', '6.EE.C.9', 'Dependent and Independent Variables', 'Use variables to represent two quantities in a real-world problem that change in relationship to one another.', 6, 'middle', 'Expressions & Equations', 'Represent and analyze quantitative relationships between dependent and independent variables', 28, 1);

-- 6.G - Geometry
INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed) VALUES
  ('math_6g_a1', 'mathematics', 'common_core', '6.G.A.1', 'Area of Polygons', 'Find the area of right triangles, other triangles, special quadrilaterals, and polygons by composing into rectangles or decomposing into triangles and other shapes.', 6, 'middle', 'Geometry', 'Solve real-world and mathematical problems involving area, surface area, and volume', 30, 1),
  ('math_6g_a2', 'mathematics', 'common_core', '6.G.A.2', 'Volume with Fractions', 'Find the volume of a right rectangular prism with fractional edge lengths.', 6, 'middle', 'Geometry', 'Solve real-world and mathematical problems involving area, surface area, and volume', 31, 1),
  ('math_6g_a3', 'mathematics', 'common_core', '6.G.A.3', 'Polygons in Coordinate Plane', 'Draw polygons in the coordinate plane given coordinates for the vertices.', 6, 'middle', 'Geometry', 'Solve real-world and mathematical problems involving area, surface area, and volume', 32, 1),
  ('math_6g_a4', 'mathematics', 'common_core', '6.G.A.4', 'Surface Area with Nets', 'Represent three-dimensional figures using nets made up of rectangles and triangles, and use the nets to find the surface area of these figures.', 6, 'middle', 'Geometry', 'Solve real-world and mathematical problems involving area, surface area, and volume', 33, 1);

-- 6.SP - Statistics and Probability
INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed) VALUES
  ('math_6sp_a1', 'mathematics', 'common_core', '6.SP.A.1', 'Statistical Questions', 'Recognize a statistical question as one that anticipates variability in the data related to the question and accounts for it in the answers.', 6, 'middle', 'Statistics & Probability', 'Develop understanding of statistical variability', 40, 1),
  ('math_6sp_a2', 'mathematics', 'common_core', '6.SP.A.2', 'Distribution Description', 'Understand that a set of data collected to answer a statistical question has a distribution which can be described by its center, spread, and overall shape.', 6, 'middle', 'Statistics & Probability', 'Develop understanding of statistical variability', 41, 1),
  ('math_6sp_a3', 'mathematics', 'common_core', '6.SP.A.3', 'Center and Variation', 'Recognize that a measure of center for a numerical data set summarizes all of its values with a single number, while a measure of variation describes how its values vary with a single number.', 6, 'middle', 'Statistics & Probability', 'Develop understanding of statistical variability', 42, 1),
  ('math_6sp_b4', 'mathematics', 'common_core', '6.SP.B.4', 'Display Data', 'Display numerical data in plots on a number line, including dot plots, histograms, and box plots.', 6, 'middle', 'Statistics & Probability', 'Summarize and describe distributions', 43, 1),
  ('math_6sp_b5', 'mathematics', 'common_core', '6.SP.B.5', 'Summarize Data Sets', 'Summarize numerical data sets in relation to their context.', 6, 'middle', 'Statistics & Probability', 'Summarize and describe distributions', 44, 1);

-- ============================================================================
-- GRADE 7 MATHEMATICS STANDARDS (Common Core) - EXTENSION
-- ============================================================================

INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed, is_extension) VALUES
  ('math_7rp_a1', 'mathematics', 'common_core', '7.RP.A.1', 'Unit Rates with Fractions', 'Compute unit rates associated with ratios of fractions, including ratios of lengths, areas and other quantities measured in like or different units.', 7, 'middle', 'Ratios & Proportions', 'Analyze proportional relationships', 50, 1, 1),
  ('math_7rp_a2', 'mathematics', 'common_core', '7.RP.A.2', 'Recognize Proportional Relationships', 'Recognize and represent proportional relationships between quantities.', 7, 'middle', 'Ratios & Proportions', 'Analyze proportional relationships', 51, 1, 1),
  ('math_7rp_a3', 'mathematics', 'common_core', '7.RP.A.3', 'Multi-step Ratio Problems', 'Use proportional relationships to solve multistep ratio and percent problems.', 7, 'middle', 'Ratios & Proportions', 'Analyze proportional relationships', 52, 1, 1),
  ('math_7ns_a1', 'mathematics', 'common_core', '7.NS.A.1', 'Add/Subtract Rational Numbers', 'Apply and extend previous understandings of addition and subtraction to add and subtract rational numbers.', 7, 'middle', 'Number System', 'Apply operations with rational numbers', 55, 1, 1),
  ('math_7ns_a2', 'mathematics', 'common_core', '7.NS.A.2', 'Multiply/Divide Rational Numbers', 'Apply and extend previous understandings of multiplication and division and of fractions to multiply and divide rational numbers.', 7, 'middle', 'Number System', 'Apply operations with rational numbers', 56, 1, 1),
  ('math_7ns_a3', 'mathematics', 'common_core', '7.NS.A.3', 'Solve Real-World Problems', 'Solve real-world and mathematical problems involving the four operations with rational numbers.', 7, 'middle', 'Number System', 'Apply operations with rational numbers', 57, 1, 1),
  ('math_7ee_a1', 'mathematics', 'common_core', '7.EE.A.1', 'Linear Expressions', 'Apply properties of operations as strategies to add, subtract, factor, and expand linear expressions with rational coefficients.', 7, 'middle', 'Expressions & Equations', 'Use properties of operations to generate equivalent expressions', 60, 1, 1),
  ('math_7ee_a2', 'mathematics', 'common_core', '7.EE.A.2', 'Rewrite Expressions', 'Understand that rewriting an expression in different forms in a problem context can shed light on the problem and how the quantities in it are related.', 7, 'middle', 'Expressions & Equations', 'Use properties of operations to generate equivalent expressions', 61, 1, 1),
  ('math_7ee_b3', 'mathematics', 'common_core', '7.EE.B.3', 'Multi-step Problems', 'Solve multi-step real-life and mathematical problems posed with positive and negative rational numbers in any form.', 7, 'middle', 'Expressions & Equations', 'Solve real-life and mathematical problems', 62, 1, 1),
  ('math_7ee_b4', 'mathematics', 'common_core', '7.EE.B.4', 'Construct and Solve Equations', 'Use variables to represent quantities in a real-world or mathematical problem, and construct simple equations and inequalities to solve problems.', 7, 'middle', 'Expressions & Equations', 'Solve real-life and mathematical problems', 63, 1, 1),
  ('math_7g_a1', 'mathematics', 'common_core', '7.G.A.1', 'Scale Drawings', 'Solve problems involving scale drawings of geometric figures, including computing actual lengths and areas from a scale drawing and reproducing a scale drawing at a different scale.', 7, 'middle', 'Geometry', 'Draw, construct, and describe geometrical figures', 70, 1, 1),
  ('math_7g_a2', 'mathematics', 'common_core', '7.G.A.2', 'Construct Triangles', 'Draw (freehand, with ruler and protractor, and with technology) geometric shapes with given conditions. Focus on constructing triangles from three measures of angles or sides.', 7, 'middle', 'Geometry', 'Draw, construct, and describe geometrical figures', 71, 1, 1),
  ('math_7g_b4', 'mathematics', 'common_core', '7.G.B.4', 'Circles', 'Know the formulas for the area and circumference of a circle and use them to solve problems.', 7, 'middle', 'Geometry', 'Solve real-life and mathematical problems involving angle measure, area, surface area, and volume', 72, 1, 1),
  ('math_7g_b5', 'mathematics', 'common_core', '7.G.B.5', 'Angle Relationships', 'Use facts about supplementary, complementary, vertical, and adjacent angles in a multi-step problem to write and solve simple equations for an unknown angle in a figure.', 7, 'middle', 'Geometry', 'Solve real-life and mathematical problems involving angle measure, area, surface area, and volume', 73, 1, 1),
  ('math_7g_b6', 'mathematics', 'common_core', '7.G.B.6', 'Area, Volume, Surface Area', 'Solve real-world and mathematical problems involving area, volume and surface area of two- and three-dimensional objects composed of triangles, quadrilaterals, polygons, cubes, and right prisms.', 7, 'middle', 'Geometry', 'Solve real-life and mathematical problems involving angle measure, area, surface area, and volume', 74, 1, 1),
  ('math_7sp_a1', 'mathematics', 'common_core', '7.SP.A.1', 'Sampling', 'Understand that statistics can be used to gain information about a population by examining a sample of the population.', 7, 'middle', 'Statistics & Probability', 'Use random sampling to draw inferences about a population', 80, 1, 1),
  ('math_7sp_b3', 'mathematics', 'common_core', '7.SP.B.3', 'Compare Distributions', 'Informally assess the degree of visual overlap of two numerical data distributions with similar variabilities.', 7, 'middle', 'Statistics & Probability', 'Draw informal comparative inferences about two populations', 81, 1, 1),
  ('math_7sp_c5', 'mathematics', 'common_core', '7.SP.C.5', 'Probability Concepts', 'Understand that the probability of a chance event is a number between 0 and 1 that expresses the likelihood of the event occurring.', 7, 'middle', 'Statistics & Probability', 'Investigate chance processes and develop, use, and evaluate probability models', 82, 1, 1),
  ('math_7sp_c6', 'mathematics', 'common_core', '7.SP.C.6', 'Experimental Probability', 'Approximate the probability of a chance event by collecting data on the chance process that produces it and observing its long-run relative frequency.', 7, 'middle', 'Statistics & Probability', 'Investigate chance processes and develop, use, and evaluate probability models', 83, 1, 1),
  ('math_7sp_c7', 'mathematics', 'common_core', '7.SP.C.7', 'Probability Models', 'Develop a probability model and use it to find probabilities of events.', 7, 'middle', 'Statistics & Probability', 'Investigate chance processes and develop, use, and evaluate probability models', 84, 1, 1),
  ('math_7sp_c8', 'mathematics', 'common_core', '7.SP.C.8', 'Compound Events', 'Find probabilities of compound events using organized lists, tables, tree diagrams, and simulation.', 7, 'middle', 'Statistics & Probability', 'Investigate chance processes and develop, use, and evaluate probability models', 85, 1, 1);

-- ============================================================================
-- GRADE 8 MATHEMATICS STANDARDS (Common Core) - ADVANCED EXTENSION
-- ============================================================================

INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed, is_extension) VALUES
  ('math_8ns_a1', 'mathematics', 'common_core', '8.NS.A.1', 'Irrational Numbers', 'Know that numbers that are not rational are called irrational. Understand informally that every number has a decimal expansion.', 8, 'middle', 'Number System', 'Know that there are numbers that are not rational', 90, 1, 1),
  ('math_8ns_a2', 'mathematics', 'common_core', '8.NS.A.2', 'Approximate Irrationals', 'Use rational approximations of irrational numbers to compare the size of irrational numbers, locate them approximately on a number line diagram.', 8, 'middle', 'Number System', 'Know that there are numbers that are not rational', 91, 1, 1),
  ('math_8ee_a1', 'mathematics', 'common_core', '8.EE.A.1', 'Integer Exponents', 'Know and apply the properties of integer exponents to generate equivalent numerical expressions.', 8, 'middle', 'Expressions & Equations', 'Work with radicals and integer exponents', 95, 1, 1),
  ('math_8ee_a2', 'mathematics', 'common_core', '8.EE.A.2', 'Square and Cube Roots', 'Use square root and cube root symbols to represent solutions to equations of the form x² = p and x³ = p.', 8, 'middle', 'Expressions & Equations', 'Work with radicals and integer exponents', 96, 1, 1),
  ('math_8ee_a3', 'mathematics', 'common_core', '8.EE.A.3', 'Scientific Notation', 'Use numbers expressed in the form of a single digit times an integer power of 10 to estimate very large or very small quantities.', 8, 'middle', 'Expressions & Equations', 'Work with radicals and integer exponents', 97, 1, 1),
  ('math_8ee_a4', 'mathematics', 'common_core', '8.EE.A.4', 'Operations with Scientific Notation', 'Perform operations with numbers expressed in scientific notation.', 8, 'middle', 'Expressions & Equations', 'Work with radicals and integer exponents', 98, 1, 1),
  ('math_8ee_b5', 'mathematics', 'common_core', '8.EE.B.5', 'Graph Proportional Relationships', 'Graph proportional relationships, interpreting the unit rate as the slope of the graph. Compare two different proportional relationships.', 8, 'middle', 'Expressions & Equations', 'Understand the connections between proportional relationships, lines, and linear equations', 100, 1, 1),
  ('math_8ee_b6', 'mathematics', 'common_core', '8.EE.B.6', 'Slope', 'Use similar triangles to explain why the slope m is the same between any two distinct points on a non-vertical line in the coordinate plane.', 8, 'middle', 'Expressions & Equations', 'Understand the connections between proportional relationships, lines, and linear equations', 101, 1, 1),
  ('math_8ee_c7', 'mathematics', 'common_core', '8.EE.C.7', 'Solve Linear Equations', 'Solve linear equations in one variable.', 8, 'middle', 'Expressions & Equations', 'Analyze and solve linear equations and pairs of simultaneous linear equations', 102, 1, 1),
  ('math_8ee_c8', 'mathematics', 'common_core', '8.EE.C.8', 'Systems of Equations', 'Analyze and solve pairs of simultaneous linear equations.', 8, 'middle', 'Expressions & Equations', 'Analyze and solve linear equations and pairs of simultaneous linear equations', 103, 1, 1),
  ('math_8f_a1', 'mathematics', 'common_core', '8.F.A.1', 'Function Definition', 'Understand that a function is a rule that assigns to each input exactly one output. The graph of a function is the set of ordered pairs consisting of an input and the corresponding output.', 8, 'middle', 'Functions', 'Define, evaluate, and compare functions', 110, 1, 1),
  ('math_8f_a2', 'mathematics', 'common_core', '8.F.A.2', 'Compare Functions', 'Compare properties of two functions each represented in a different way (algebraically, graphically, numerically in tables, or by verbal descriptions).', 8, 'middle', 'Functions', 'Define, evaluate, and compare functions', 111, 1, 1),
  ('math_8f_a3', 'mathematics', 'common_core', '8.F.A.3', 'Linear Functions', 'Interpret the equation y = mx + b as defining a linear function, whose graph is a straight line.', 8, 'middle', 'Functions', 'Define, evaluate, and compare functions', 112, 1, 1),
  ('math_8f_b4', 'mathematics', 'common_core', '8.F.B.4', 'Model with Functions', 'Construct a function to model a linear relationship between two quantities.', 8, 'middle', 'Functions', 'Use functions to model relationships between quantities', 113, 1, 1),
  ('math_8f_b5', 'mathematics', 'common_core', '8.F.B.5', 'Analyze Functions', 'Describe qualitatively the functional relationship between two quantities by analyzing a graph.', 8, 'middle', 'Functions', 'Use functions to model relationships between quantities', 114, 1, 1),
  ('math_8g_a1', 'mathematics', 'common_core', '8.G.A.1', 'Transformations', 'Verify experimentally the properties of rotations, reflections, and translations.', 8, 'middle', 'Geometry', 'Understand congruence and similarity using physical models, transparencies, or geometry software', 120, 1, 1),
  ('math_8g_a2', 'mathematics', 'common_core', '8.G.A.2', 'Congruence', 'Understand that a two-dimensional figure is congruent to another if the second can be obtained from the first by a sequence of rotations, reflections, and translations.', 8, 'middle', 'Geometry', 'Understand congruence and similarity using physical models, transparencies, or geometry software', 121, 1, 1),
  ('math_8g_a3', 'mathematics', 'common_core', '8.G.A.3', 'Dilations', 'Describe the effect of dilations, translations, rotations, and reflections on two-dimensional figures using coordinates.', 8, 'middle', 'Geometry', 'Understand congruence and similarity using physical models, transparencies, or geometry software', 122, 1, 1),
  ('math_8g_a4', 'mathematics', 'common_core', '8.G.A.4', 'Similarity', 'Understand that a two-dimensional figure is similar to another if the second can be obtained from the first by a sequence of rotations, reflections, translations, and dilations.', 8, 'middle', 'Geometry', 'Understand congruence and similarity using physical models, transparencies, or geometry software', 123, 1, 1),
  ('math_8g_b6', 'mathematics', 'common_core', '8.G.B.6', 'Pythagorean Theorem Proof', 'Explain a proof of the Pythagorean Theorem and its converse.', 8, 'middle', 'Geometry', 'Understand and apply the Pythagorean Theorem', 125, 1, 1),
  ('math_8g_b7', 'mathematics', 'common_core', '8.G.B.7', 'Apply Pythagorean Theorem', 'Apply the Pythagorean Theorem to determine unknown side lengths in right triangles in real-world and mathematical problems in two and three dimensions.', 8, 'middle', 'Geometry', 'Understand and apply the Pythagorean Theorem', 126, 1, 1),
  ('math_8g_b8', 'mathematics', 'common_core', '8.G.B.8', 'Distance Formula', 'Apply the Pythagorean Theorem to find the distance between two points in a coordinate system.', 8, 'middle', 'Geometry', 'Understand and apply the Pythagorean Theorem', 127, 1, 1),
  ('math_8g_c9', 'mathematics', 'common_core', '8.G.C.9', 'Volume Formulas', 'Know the formulas for the volumes of cones, cylinders, and spheres and use them to solve real-world and mathematical problems.', 8, 'middle', 'Geometry', 'Solve real-world and mathematical problems involving volume of cylinders, cones, and spheres', 128, 1, 1),
  ('math_8sp_a1', 'mathematics', 'common_core', '8.SP.A.1', 'Scatter Plots', 'Construct and interpret scatter plots for bivariate measurement data to investigate patterns of association between two quantities.', 8, 'middle', 'Statistics & Probability', 'Investigate patterns of association in bivariate data', 130, 1, 1),
  ('math_8sp_a2', 'mathematics', 'common_core', '8.SP.A.2', 'Line of Best Fit', 'Know that straight lines are widely used to model relationships between two quantitative variables.', 8, 'middle', 'Statistics & Probability', 'Investigate patterns of association in bivariate data', 131, 1, 1),
  ('math_8sp_a3', 'mathematics', 'common_core', '8.SP.A.3', 'Slope and Intercept', 'Use the equation of a linear model to solve problems in the context of bivariate measurement data, interpreting the slope and intercept.', 8, 'middle', 'Statistics & Probability', 'Investigate patterns of association in bivariate data', 132, 1, 1),
  ('math_8sp_a4', 'mathematics', 'common_core', '8.SP.A.4', 'Two-Way Tables', 'Understand that patterns of association can also be seen in bivariate categorical data by displaying frequencies and relative frequencies in a two-way table.', 8, 'middle', 'Statistics & Probability', 'Investigate patterns of association in bivariate data', 133, 1, 1);

-- ============================================================================
-- HYRO ADVANCED EXTENSIONS - Beyond Common Core
-- ============================================================================

INSERT OR IGNORE INTO hyro_learning_standards (id, domain, standard_set, standard_code, title, description, grade_level, grade_band, strand, cluster, sequence_order, is_assessed, is_extension) VALUES
  ('math_adv_algebra_intro', 'mathematics', 'hyro_advanced', 'ADV.ALG.1', 'Introduction to Algebra', 'Foundational algebraic thinking including pattern recognition, function notation, and abstract reasoning.', NULL, 'advanced', 'Algebra', 'Algebraic Foundations', 200, 0, 1),
  ('math_adv_quadratics', 'mathematics', 'hyro_advanced', 'ADV.ALG.2', 'Quadratic Expressions', 'Introduction to quadratic expressions, factoring, and the quadratic formula.', NULL, 'advanced', 'Algebra', 'Quadratics', 201, 0, 1),
  ('math_adv_exponential', 'mathematics', 'hyro_advanced', 'ADV.ALG.3', 'Exponential Functions', 'Understanding exponential growth and decay, compound interest, and exponential equations.', NULL, 'advanced', 'Algebra', 'Exponential Functions', 202, 0, 1),
  ('math_adv_logic', 'mathematics', 'hyro_advanced', 'ADV.LOG.1', 'Mathematical Logic', 'Introduction to formal logic, truth tables, and logical reasoning in mathematics.', NULL, 'advanced', 'Logic', 'Foundations', 210, 0, 1),
  ('math_adv_proofs', 'mathematics', 'hyro_advanced', 'ADV.LOG.2', 'Introduction to Proofs', 'Basic proof techniques including direct proof, proof by contradiction, and mathematical induction.', NULL, 'advanced', 'Logic', 'Proofs', 211, 0, 1),
  ('math_adv_number_theory', 'mathematics', 'hyro_advanced', 'ADV.NT.1', 'Number Theory Basics', 'Prime numbers, divisibility rules, modular arithmetic, and cryptographic applications.', NULL, 'advanced', 'Number Theory', 'Foundations', 220, 0, 1),
  ('math_adv_combinatorics', 'mathematics', 'hyro_advanced', 'ADV.COMB.1', 'Combinatorics', 'Permutations, combinations, counting principles, and probability connections.', NULL, 'advanced', 'Discrete Math', 'Combinatorics', 230, 0, 1),
  ('math_adv_geometry_proofs', 'mathematics', 'hyro_advanced', 'ADV.GEO.1', 'Geometric Proofs', 'Formal geometric proofs, triangle congruence theorems, and logical reasoning in geometry.', NULL, 'advanced', 'Geometry', 'Proofs', 240, 0, 1),
  ('math_adv_trig_intro', 'mathematics', 'hyro_advanced', 'ADV.TRIG.1', 'Introduction to Trigonometry', 'Right triangle trigonometry, sine, cosine, tangent, and real-world applications.', NULL, 'advanced', 'Trigonometry', 'Foundations', 250, 0, 1);

-- ============================================================================
-- CURRICULUM TOPICS - GRADE 6 MATHEMATICS
-- Breaking standards into learnable topics
-- ============================================================================

-- 6.RP Topics - Ratios and Proportional Relationships
INSERT OR IGNORE INTO hyro_curriculum_topics (id, domain, standard_id, topic, description, learning_objectives, difficulty_tier, estimated_minutes) VALUES
  ('topic_math_ratio_intro', 'mathematics', 'math_6rp_a1', 'Introduction to Ratios', 'Understanding what ratios are and how to express them', '["Define ratio as a comparison of two quantities", "Express ratios in three forms: a:b, a/b, and a to b", "Identify ratios in real-world contexts"]', 1, 20),
  ('topic_math_ratio_language', 'mathematics', 'math_6rp_a1', 'Ratio Language', 'Using proper mathematical language to describe ratios', '["Use phrases like for every, for each, per", "Distinguish between part-to-part and part-to-whole ratios", "Translate between verbal and symbolic ratio representations"]', 1, 15),
  ('topic_math_equivalent_ratios', 'mathematics', 'math_6rp_a3a', 'Equivalent Ratios', 'Finding and recognizing equivalent ratios', '["Generate equivalent ratios by multiplying or dividing", "Determine if two ratios are equivalent", "Use ratio tables to organize equivalent ratios"]', 2, 25),
  ('topic_math_ratio_tables', 'mathematics', 'math_6rp_a3a', 'Ratio Tables', 'Creating and using ratio tables to solve problems', '["Construct ratio tables from problem contexts", "Use ratio tables to find missing values", "Identify patterns in ratio tables"]', 2, 30),
  ('topic_math_unit_rate_concept', 'mathematics', 'math_6rp_a2', 'Understanding Unit Rates', 'The concept of unit rate as a ratio with denominator 1', '["Define unit rate as a rate per one unit", "Calculate unit rates from given ratios", "Interpret unit rates in context"]', 2, 25),
  ('topic_math_unit_rate_problems', 'mathematics', 'math_6rp_a3b', 'Solving Unit Rate Problems', 'Applying unit rates to solve real-world problems', '["Use unit rates to compare prices (unit pricing)", "Solve constant speed problems using unit rates", "Choose the better deal using unit rate comparisons"]', 2, 30),
  ('topic_math_percent_concept', 'mathematics', 'math_6rp_a3c', 'Understanding Percent', 'Percent as a rate per 100', '["Define percent as per hundred", "Convert between fractions, decimals, and percents", "Recognize common percent equivalents"]', 2, 25),
  ('topic_math_percent_of_number', 'mathematics', 'math_6rp_a3c', 'Finding Percent of a Number', 'Calculating a percent of a quantity', '["Calculate percent of a number using multiplication", "Use proportional reasoning for percent problems", "Estimate percents mentally"]', 2, 30),
  ('topic_math_percent_problems', 'mathematics', 'math_6rp_a3c', 'Percent Word Problems', 'Solving various percent problem types', '["Find the part given whole and percent", "Find the whole given part and percent", "Find the percent given part and whole"]', 3, 35),
  ('topic_math_unit_conversion', 'mathematics', 'math_6rp_a3d', 'Unit Conversion', 'Converting between measurement units using ratios', '["Convert within the same measurement system", "Set up and solve conversion proportions", "Use dimensional analysis for multi-step conversions"]', 2, 30);

-- 6.NS Topics - The Number System
INSERT OR IGNORE INTO hyro_curriculum_topics (id, domain, standard_id, topic, description, learning_objectives, difficulty_tier, estimated_minutes) VALUES
  ('topic_math_divide_fractions_concept', 'mathematics', 'math_6ns_a1', 'Understanding Fraction Division', 'The meaning of dividing fractions', '["Interpret division of fractions using models", "Understand keep-change-flip rule conceptually", "Relate fraction division to multiplication"]', 2, 30),
  ('topic_math_divide_fractions_procedure', 'mathematics', 'math_6ns_a1', 'Dividing Fractions Procedure', 'Computing quotients of fractions', '["Apply the standard algorithm for fraction division", "Divide mixed numbers", "Simplify quotients"]', 2, 25),
  ('topic_math_divide_fractions_word', 'mathematics', 'math_6ns_a1', 'Fraction Division Word Problems', 'Solving real-world problems with fraction division', '["Identify when to divide fractions in context", "Set up fraction division problems from word problems", "Interpret quotients in context"]', 3, 35),
  ('topic_math_long_division', 'mathematics', 'math_6ns_b2', 'Long Division Fluency', 'Dividing multi-digit numbers efficiently', '["Apply standard long division algorithm", "Check division with multiplication", "Interpret remainders appropriately"]', 2, 30),
  ('topic_math_decimal_add_sub', 'mathematics', 'math_6ns_b3', 'Adding and Subtracting Decimals', 'Computing with decimal numbers', '["Align decimal points for addition/subtraction", "Add and subtract decimals fluently", "Estimate decimal sums and differences"]', 1, 20),
  ('topic_math_decimal_mult', 'mathematics', 'math_6ns_b3', 'Multiplying Decimals', 'Multiplying decimal numbers', '["Apply the standard algorithm for decimal multiplication", "Place decimal point correctly in products", "Estimate decimal products"]', 2, 25),
  ('topic_math_decimal_div', 'mathematics', 'math_6ns_b3', 'Dividing Decimals', 'Dividing decimal numbers', '["Divide decimals by whole numbers", "Divide decimals by decimals", "Round quotients appropriately"]', 2, 30),
  ('topic_math_gcf', 'mathematics', 'math_6ns_b4', 'Greatest Common Factor', 'Finding the GCF of two numbers', '["List factors of numbers systematically", "Identify common factors", "Find GCF using various methods"]', 2, 25),
  ('topic_math_lcm', 'mathematics', 'math_6ns_b4', 'Least Common Multiple', 'Finding the LCM of two numbers', '["List multiples of numbers", "Identify common multiples", "Find LCM using various methods"]', 2, 25),
  ('topic_math_gcf_lcm_problems', 'mathematics', 'math_6ns_b4', 'GCF and LCM Applications', 'Using GCF and LCM to solve problems', '["Apply GCF to simplify fractions", "Apply LCM to find common denominators", "Solve word problems requiring GCF or LCM"]', 3, 30),
  ('topic_math_integers_intro', 'mathematics', 'math_6ns_c5', 'Introduction to Integers', 'Understanding positive and negative numbers', '["Understand integers as positive, negative, and zero", "Represent integers on a number line", "Interpret integers in real-world contexts"]', 1, 20),
  ('topic_math_opposites', 'mathematics', 'math_6ns_c5', 'Opposites and Zero', 'Understanding opposite numbers and zero', '["Define and find opposites of numbers", "Understand that opposites sum to zero", "Locate opposites on the number line"]', 1, 15),
  ('topic_math_rational_numberline', 'mathematics', 'math_6ns_c6', 'Rational Numbers on Number Line', 'Placing rational numbers on the number line', '["Plot positive and negative fractions", "Plot positive and negative decimals", "Identify positions between integers"]', 2, 25),
  ('topic_math_coordinate_plane', 'mathematics', 'math_6ns_c6', 'The Coordinate Plane', 'Understanding the four-quadrant coordinate plane', '["Identify quadrants and axes", "Plot ordered pairs in all quadrants", "Identify coordinates of plotted points"]', 2, 25),
  ('topic_math_ordering_rationals', 'mathematics', 'math_6ns_c7', 'Ordering Rational Numbers', 'Comparing and ordering positive and negative numbers', '["Compare rational numbers using inequality symbols", "Order sets of rational numbers", "Use number line to justify comparisons"]', 2, 25),
  ('topic_math_absolute_value', 'mathematics', 'math_6ns_c7', 'Absolute Value', 'Understanding and computing absolute value', '["Define absolute value as distance from zero", "Compute absolute value of numbers", "Compare absolute values"]', 2, 20),
  ('topic_math_coordinate_problems', 'mathematics', 'math_6ns_c8', 'Coordinate Plane Problems', 'Solving problems on the coordinate plane', '["Find distances on the coordinate plane", "Reflect points across axes", "Solve real-world problems using coordinates"]', 3, 35);

-- 6.EE Topics - Expressions and Equations
INSERT OR IGNORE INTO hyro_curriculum_topics (id, domain, standard_id, topic, description, learning_objectives, difficulty_tier, estimated_minutes) VALUES
  ('topic_math_exponents_intro', 'mathematics', 'math_6ee_a1', 'Introduction to Exponents', 'Understanding exponential notation', '["Write repeated multiplication using exponents", "Evaluate expressions with exponents", "Understand base and exponent terminology"]', 1, 20),
  ('topic_math_order_operations', 'mathematics', 'math_6ee_a1', 'Order of Operations with Exponents', 'Evaluating expressions with PEMDAS', '["Apply order of operations correctly", "Evaluate expressions with parentheses and exponents", "Identify common order of operations errors"]', 2, 25),
  ('topic_math_variables_intro', 'mathematics', 'math_6ee_a2', 'Introduction to Variables', 'Understanding variables as placeholders', '["Understand that letters can represent numbers", "Evaluate expressions for given variable values", "Distinguish between variables and constants"]', 1, 20),
  ('topic_math_write_expressions', 'mathematics', 'math_6ee_a2', 'Writing Algebraic Expressions', 'Translating words to algebraic expressions', '["Translate verbal phrases to expressions", "Identify key words for operations", "Write expressions for real-world situations"]', 2, 30),
  ('topic_math_properties_operations', 'mathematics', 'math_6ee_a3', 'Properties of Operations', 'Using commutative, associative, and distributive properties', '["Identify and apply the commutative property", "Identify and apply the associative property", "Apply the distributive property"]', 2, 30),
  ('topic_math_equivalent_expressions', 'mathematics', 'math_6ee_a4', 'Generating Equivalent Expressions', 'Creating and identifying equivalent expressions', '["Use properties to create equivalent expressions", "Combine like terms", "Determine if two expressions are equivalent"]', 2, 30),
  ('topic_math_equations_intro', 'mathematics', 'math_6ee_b5', 'Introduction to Equations', 'Understanding equations and solutions', '["Define equation as a statement of equality", "Understand solution as a value that makes equation true", "Test values to check if they are solutions"]', 1, 20),
  ('topic_math_write_equations', 'mathematics', 'math_6ee_b6', 'Writing Equations', 'Representing situations with equations', '["Write equations from word problems", "Use variables appropriately in equations", "Translate between verbal and symbolic forms"]', 2, 30),
  ('topic_math_solve_add_sub', 'mathematics', 'math_6ee_b7', 'Solving Addition/Subtraction Equations', 'Solving one-step equations', '["Solve x + p = q using inverse operations", "Solve x - p = q using inverse operations", "Check solutions by substitution"]', 2, 25),
  ('topic_math_solve_mult_div', 'mathematics', 'math_6ee_b7', 'Solving Multiplication/Division Equations', 'Solving one-step equations', '["Solve px = q using inverse operations", "Solve x/p = q using inverse operations", "Interpret solutions in context"]', 2, 25),
  ('topic_math_inequalities_intro', 'mathematics', 'math_6ee_b8', 'Introduction to Inequalities', 'Understanding and writing inequalities', '["Understand inequality symbols", "Write inequalities from verbal descriptions", "Graph inequalities on number line"]', 2, 25),
  ('topic_math_dependent_independent', 'mathematics', 'math_6ee_c9', 'Dependent and Independent Variables', 'Understanding variable relationships', '["Identify independent and dependent variables", "Write equations showing relationships", "Create tables showing relationships"]', 2, 30);

-- Continue with more topics...
-- (Geometry, Statistics topics would follow the same pattern)

-- ============================================================================
-- QUESTION BANK - MATHEMATICS GRADE 6
-- Comprehensive question set with varied difficulty and types
-- ============================================================================

-- Ratios and Proportional Relationships Questions
INSERT OR IGNORE INTO hyro_question_bank (id, domain, standard_id, topic_id, question_type, question_text, answer_options, correct_answer, explanation, difficulty, difficulty_tier, bloom_level, dok_level, hints) VALUES
  -- Basic Ratio Questions (Tier 1)
  ('q_math_ratio_001', 'mathematics', 'math_6rp_a1', 'topic_math_ratio_intro', 'multiple_choice', 'In a bag of marbles, there are 4 red marbles and 6 blue marbles. What is the ratio of red marbles to blue marbles?', '["4:6", "6:4", "4:10", "2:5"]', '4:6', 'The ratio of red to blue is the number of red (4) compared to the number of blue (6), written as 4:6. This can also be simplified to 2:3.', 25, 1, 'remember', 1, '["Count the red marbles first", "Count the blue marbles second", "Write them in order: red to blue"]'),
  ('q_math_ratio_002', 'mathematics', 'math_6rp_a1', 'topic_math_ratio_intro', 'multiple_choice', 'Which of the following represents the same ratio as 3:5?', '["6:10", "5:3", "9:12", "3:10"]', '6:10', 'To find an equivalent ratio, multiply both parts by the same number. 3×2=6 and 5×2=10, so 6:10 is equivalent to 3:5.', 30, 1, 'understand', 2, '["Try multiplying both parts of 3:5 by 2", "Check if the fraction 6/10 equals 3/5"]'),
  ('q_math_ratio_003', 'mathematics', 'math_6rp_a1', 'topic_math_ratio_intro', 'short_answer', 'A recipe calls for 2 cups of flour for every 3 cups of sugar. Write this as a ratio of flour to sugar.', NULL, '2:3', 'The ratio is flour to sugar, so we write the flour amount first (2) then the sugar amount (3), giving us 2:3.', 20, 1, 'remember', 1, '["What comes first in flour to sugar?", "Write the flour amount, then the sugar amount"]'),
  ('q_math_ratio_004', 'mathematics', 'math_6rp_a1', 'topic_math_ratio_language', 'multiple_choice', 'The ratio of boys to girls in a class is 3 to 5. If there are 15 boys, how many girls are there?', '["9", "20", "25", "30"]', '25', 'Set up the proportion: 3/5 = 15/x. If 3 boys correspond to 5 girls, then 15 boys (3×5) correspond to 25 girls (5×5).', 40, 2, 'apply', 2, '["What number times 3 gives 15?", "Multiply 5 by that same number"]'),

  -- Unit Rate Questions (Tier 2)
  ('q_math_unit_rate_001', 'mathematics', 'math_6rp_a2', 'topic_math_unit_rate_concept', 'multiple_choice', 'A car travels 180 miles in 3 hours. What is the unit rate in miles per hour?', '["60 miles per hour", "540 miles per hour", "3 miles per hour", "180 miles per hour"]', '60 miles per hour', 'Unit rate means per one hour. Divide 180 miles by 3 hours: 180÷3 = 60 miles per hour.', 35, 2, 'apply', 2, '["Unit rate is per ONE hour", "Divide the miles by the hours"]'),
  ('q_math_unit_rate_002', 'mathematics', 'math_6rp_a3b', 'topic_math_unit_rate_problems', 'multiple_choice', 'Store A sells 5 apples for $3.00. Store B sells 8 apples for $5.00. Which store has the better price per apple?', '["Store A ($0.60 per apple)", "Store B ($0.625 per apple)", "They are the same price", "Cannot be determined"]', 'Store A ($0.60 per apple)', 'Store A: $3.00÷5 = $0.60 per apple. Store B: $5.00÷8 = $0.625 per apple. Store A is cheaper.', 45, 2, 'analyze', 3, '["Find the price per apple at each store", "Divide the total price by the number of apples", "Compare the unit prices"]'),
  ('q_math_unit_rate_003', 'mathematics', 'math_6rp_a3b', 'topic_math_unit_rate_problems', 'short_answer', 'A printer prints 45 pages in 5 minutes. How many pages does it print per minute?', NULL, '9', 'Unit rate = 45 pages ÷ 5 minutes = 9 pages per minute.', 30, 2, 'apply', 2, '["Divide pages by minutes"]'),

  -- Percent Questions (Tier 2-3)
  ('q_math_percent_001', 'mathematics', 'math_6rp_a3c', 'topic_math_percent_concept', 'multiple_choice', 'What is 25% expressed as a fraction in lowest terms?', '["1/4", "1/25", "25/10", "2/5"]', '1/4', '25% means 25 per 100, or 25/100. Simplified: 25/100 = 1/4.', 30, 2, 'understand', 1, '["Percent means per 100", "Write as a fraction over 100", "Simplify by dividing numerator and denominator by 25"]'),
  ('q_math_percent_002', 'mathematics', 'math_6rp_a3c', 'topic_math_percent_of_number', 'multiple_choice', 'What is 30% of 80?', '["24", "30", "50", "110"]', '24', '30% of 80 = 0.30 × 80 = 24. Or: (30/100) × 80 = 2400/100 = 24.', 35, 2, 'apply', 2, '["Convert 30% to a decimal (0.30)", "Multiply by 80"]'),
  ('q_math_percent_003', 'mathematics', 'math_6rp_a3c', 'topic_math_percent_problems', 'multiple_choice', 'A shirt originally costs $40. It is on sale for 15% off. What is the sale price?', '["$34", "$25", "$6", "$46"]', '$34', 'Discount = 15% of $40 = 0.15 × 40 = $6. Sale price = $40 - $6 = $34.', 45, 2, 'apply', 2, '["First find 15% of $40", "Then subtract from the original price"]'),
  ('q_math_percent_004', 'mathematics', 'math_6rp_a3c', 'topic_math_percent_problems', 'multiple_choice', '18 is what percent of 72?', '["25%", "18%", "54%", "4%"]', '25%', 'Percent = (part/whole) × 100 = (18/72) × 100 = 0.25 × 100 = 25%.', 50, 3, 'apply', 2, '["Divide the part by the whole", "Multiply by 100 to get the percent"]'),
  ('q_math_percent_005', 'mathematics', 'math_6rp_a3c', 'topic_math_percent_problems', 'short_answer', 'If 40% of a number is 28, what is the number?', NULL, '70', 'Let x = the number. 0.40x = 28. x = 28 ÷ 0.40 = 70.', 55, 3, 'apply', 3, '["Set up equation: 40% of x = 28", "Divide 28 by 0.40"]'),

  -- Fraction Division Questions
  ('q_math_frac_div_001', 'mathematics', 'math_6ns_a1', 'topic_math_divide_fractions_procedure', 'multiple_choice', 'What is 2/3 ÷ 1/4?', '["8/3", "2/12", "1/6", "8/12"]', '8/3', 'To divide fractions, multiply by the reciprocal: 2/3 ÷ 1/4 = 2/3 × 4/1 = 8/3.', 40, 2, 'apply', 2, '["Keep the first fraction", "Change division to multiplication", "Flip the second fraction"]'),
  ('q_math_frac_div_002', 'mathematics', 'math_6ns_a1', 'topic_math_divide_fractions_procedure', 'multiple_choice', 'Divide: 3/4 ÷ 2/5', '["15/8", "6/20", "5/8", "8/15"]', '15/8', '3/4 ÷ 2/5 = 3/4 × 5/2 = 15/8.', 40, 2, 'apply', 2, '["Multiply 3/4 by the reciprocal of 2/5", "The reciprocal of 2/5 is 5/2"]'),
  ('q_math_frac_div_003', 'mathematics', 'math_6ns_a1', 'topic_math_divide_fractions_word', 'multiple_choice', 'A recipe needs 3/4 cup of sugar. How many recipes can you make with 6 cups of sugar?', '["8 recipes", "4 1/2 recipes", "6 recipes", "18 recipes"]', '8 recipes', '6 ÷ 3/4 = 6 × 4/3 = 24/3 = 8 recipes.', 50, 3, 'apply', 3, '["Divide 6 by 3/4", "Write 6 as 6/1 first"]'),

  -- GCF and LCM Questions
  ('q_math_gcf_001', 'mathematics', 'math_6ns_b4', 'topic_math_gcf', 'multiple_choice', 'What is the greatest common factor (GCF) of 24 and 36?', '["12", "6", "4", "72"]', '12', 'Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24. Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36. Common factors: 1, 2, 3, 4, 6, 12. GCF = 12.', 40, 2, 'apply', 2, '["List factors of 24", "List factors of 36", "Find the largest factor they share"]'),
  ('q_math_lcm_001', 'mathematics', 'math_6ns_b4', 'topic_math_lcm', 'multiple_choice', 'What is the least common multiple (LCM) of 4 and 6?', '["12", "24", "2", "10"]', '12', 'Multiples of 4: 4, 8, 12, 16... Multiples of 6: 6, 12, 18... The smallest common multiple is 12.', 40, 2, 'apply', 2, '["List multiples of 4", "List multiples of 6", "Find the smallest they share"]'),

  -- Integer Questions
  ('q_math_int_001', 'mathematics', 'math_6ns_c5', 'topic_math_integers_intro', 'multiple_choice', 'Which integer represents 50 feet below sea level?', '["-50", "50", "-100", "0"]', '-50', 'Below sea level is negative. 50 feet below is represented as -50.', 25, 1, 'understand', 1, '["Below sea level means negative", "The number is 50"]'),
  ('q_math_int_002', 'mathematics', 'math_6ns_c7', 'topic_math_absolute_value', 'multiple_choice', 'What is the absolute value of -8?', '["8", "-8", "0", "16"]', '8', 'Absolute value is the distance from zero, which is always positive. |-8| = 8.', 30, 2, 'understand', 1, '["Absolute value measures distance from zero", "Distance is always positive"]'),
  ('q_math_int_003', 'mathematics', 'math_6ns_c7', 'topic_math_ordering_rationals', 'multiple_choice', 'Which list shows the numbers in order from least to greatest? -5, 3, -2, 0, 1', '["−5, −2, 0, 1, 3", "3, 1, 0, −2, −5", "0, 1, −2, 3, −5", "−2, −5, 0, 1, 3"]', '−5, −2, 0, 1, 3', 'On a number line, numbers increase left to right. -5 is furthest left, then -2, then 0, 1, and 3.', 35, 2, 'apply', 2, '["Negative numbers are less than 0", "More negative = smaller value"]'),

  -- Coordinate Plane Questions
  ('q_math_coord_001', 'mathematics', 'math_6ns_c6', 'topic_math_coordinate_plane', 'multiple_choice', 'In which quadrant is the point (-3, 5) located?', '["Quadrant II", "Quadrant I", "Quadrant III", "Quadrant IV"]', 'Quadrant II', 'Quadrant II has negative x (left of y-axis) and positive y (above x-axis). (-3, 5) has x=-3 (negative) and y=5 (positive).', 40, 2, 'apply', 2, '["Check if x is positive or negative", "Check if y is positive or negative", "Quadrant II: x negative, y positive"]'),

  -- Expressions and Equations Questions
  ('q_math_exp_001', 'mathematics', 'math_6ee_a1', 'topic_math_exponents_intro', 'multiple_choice', 'What is the value of 2⁴?', '["16", "8", "6", "24"]', '16', '2⁴ means 2 × 2 × 2 × 2 = 16.', 25, 1, 'apply', 1, '["The exponent tells you how many times to multiply", "2⁴ = 2 × 2 × 2 × 2"]'),
  ('q_math_exp_002', 'mathematics', 'math_6ee_a1', 'topic_math_order_operations', 'multiple_choice', 'Evaluate: 3 + 4 × 2²', '["19", "28", "49", "14"]', '19', 'Order of operations: First 2² = 4, then 4 × 4 = 16, finally 3 + 16 = 19.', 40, 2, 'apply', 2, '["PEMDAS: Exponents before multiplication", "Multiplication before addition"]'),
  ('q_math_exp_003', 'mathematics', 'math_6ee_a2', 'topic_math_variables_intro', 'multiple_choice', 'If x = 5, what is the value of 3x + 7?', '["22", "15", "45", "37"]', '22', 'Substitute x = 5: 3(5) + 7 = 15 + 7 = 22.', 30, 2, 'apply', 2, '["Replace x with 5", "Multiply first, then add"]'),
  ('q_math_exp_004', 'mathematics', 'math_6ee_a2', 'topic_math_write_expressions', 'multiple_choice', 'Which expression represents "5 less than twice a number n"?', '["2n - 5", "5 - 2n", "2(n - 5)", "5 - n/2"]', '2n - 5', '"Twice a number" is 2n. "5 less than" means subtract 5. So: 2n - 5.', 45, 2, 'apply', 2, '["Twice a number = 2n", "Less than means subtract from"]'),
  ('q_math_exp_005', 'mathematics', 'math_6ee_a3', 'topic_math_properties_operations', 'multiple_choice', 'Use the distributive property to expand: 4(x + 3)', '["4x + 12", "4x + 3", "x + 12", "4x + 7"]', '4x + 12', 'Distributive property: 4(x + 3) = 4·x + 4·3 = 4x + 12.', 35, 2, 'apply', 2, '["Multiply 4 by each term inside", "4 × x and 4 × 3"]'),

  -- Solving Equations Questions
  ('q_math_eq_001', 'mathematics', 'math_6ee_b7', 'topic_math_solve_add_sub', 'multiple_choice', 'Solve: x + 8 = 15', '["x = 7", "x = 23", "x = 8", "x = 120"]', 'x = 7', 'Subtract 8 from both sides: x + 8 - 8 = 15 - 8, so x = 7.', 30, 2, 'apply', 2, '["What operation will undo adding 8?", "Subtract 8 from both sides"]'),
  ('q_math_eq_002', 'mathematics', 'math_6ee_b7', 'topic_math_solve_mult_div', 'multiple_choice', 'Solve: 6x = 42', '["x = 7", "x = 36", "x = 48", "x = 252"]', 'x = 7', 'Divide both sides by 6: 6x ÷ 6 = 42 ÷ 6, so x = 7.', 30, 2, 'apply', 2, '["What operation will undo multiplying by 6?", "Divide both sides by 6"]'),
  ('q_math_eq_003', 'mathematics', 'math_6ee_b7', 'topic_math_solve_mult_div', 'short_answer', 'Solve: x/5 = 9', NULL, '45', 'Multiply both sides by 5: (x/5) × 5 = 9 × 5, so x = 45.', 35, 2, 'apply', 2, '["Multiply both sides by 5"]');

-- More questions would continue for each standard and topic...
-- This gives a solid foundation of 30+ math questions

-- ============================================================================
-- PREREQUISITES FOR MATH TOPICS
-- ============================================================================

INSERT OR IGNORE INTO hyro_skill_prerequisites (id, skill_id, skill_type, prerequisite_id, prerequisite_type, strength) VALUES
  -- Ratio prerequisites
  ('prereq_ratio_001', 'topic_math_equivalent_ratios', 'topic', 'topic_math_ratio_intro', 'topic', 'required'),
  ('prereq_ratio_002', 'topic_math_ratio_tables', 'topic', 'topic_math_equivalent_ratios', 'topic', 'required'),
  ('prereq_ratio_003', 'topic_math_unit_rate_concept', 'topic', 'topic_math_ratio_intro', 'topic', 'required'),
  ('prereq_ratio_004', 'topic_math_unit_rate_problems', 'topic', 'topic_math_unit_rate_concept', 'topic', 'required'),
  ('prereq_ratio_005', 'topic_math_percent_of_number', 'topic', 'topic_math_percent_concept', 'topic', 'required'),
  ('prereq_ratio_006', 'topic_math_percent_problems', 'topic', 'topic_math_percent_of_number', 'topic', 'required'),

  -- Number system prerequisites
  ('prereq_ns_001', 'topic_math_divide_fractions_procedure', 'topic', 'topic_math_divide_fractions_concept', 'topic', 'required'),
  ('prereq_ns_002', 'topic_math_divide_fractions_word', 'topic', 'topic_math_divide_fractions_procedure', 'topic', 'required'),
  ('prereq_ns_003', 'topic_math_decimal_mult', 'topic', 'topic_math_decimal_add_sub', 'topic', 'required'),
  ('prereq_ns_004', 'topic_math_decimal_div', 'topic', 'topic_math_decimal_mult', 'topic', 'required'),
  ('prereq_ns_005', 'topic_math_gcf_lcm_problems', 'topic', 'topic_math_gcf', 'topic', 'required'),
  ('prereq_ns_006', 'topic_math_gcf_lcm_problems', 'topic', 'topic_math_lcm', 'topic', 'required'),
  ('prereq_ns_007', 'topic_math_rational_numberline', 'topic', 'topic_math_integers_intro', 'topic', 'required'),
  ('prereq_ns_008', 'topic_math_coordinate_plane', 'topic', 'topic_math_rational_numberline', 'topic', 'required'),
  ('prereq_ns_009', 'topic_math_absolute_value', 'topic', 'topic_math_integers_intro', 'topic', 'required'),
  ('prereq_ns_010', 'topic_math_ordering_rationals', 'topic', 'topic_math_absolute_value', 'topic', 'recommended'),
  ('prereq_ns_011', 'topic_math_coordinate_problems', 'topic', 'topic_math_coordinate_plane', 'topic', 'required'),

  -- Expressions and equations prerequisites
  ('prereq_ee_001', 'topic_math_order_operations', 'topic', 'topic_math_exponents_intro', 'topic', 'required'),
  ('prereq_ee_002', 'topic_math_write_expressions', 'topic', 'topic_math_variables_intro', 'topic', 'required'),
  ('prereq_ee_003', 'topic_math_equivalent_expressions', 'topic', 'topic_math_properties_operations', 'topic', 'required'),
  ('prereq_ee_004', 'topic_math_write_equations', 'topic', 'topic_math_equations_intro', 'topic', 'required'),
  ('prereq_ee_005', 'topic_math_solve_add_sub', 'topic', 'topic_math_equations_intro', 'topic', 'required'),
  ('prereq_ee_006', 'topic_math_solve_mult_div', 'topic', 'topic_math_solve_add_sub', 'topic', 'recommended'),
  ('prereq_ee_007', 'topic_math_inequalities_intro', 'topic', 'topic_math_equations_intro', 'topic', 'required');
