/**
 * Apply contact merge suggestions generated by ingest-relationships.
 *
 * - Reads .data/contact_merge_suggestions.jsonl
 * - Applies entries with confidence >= threshold (default 0.85)
 * - Updates contacts table (canonical_handle, confidence) if handle exists
 *
 * Usage:
 *   CONF_THRESHOLD=0.85 npx tsx scripts/apply-contact-suggestions.ts
 */
import fs from 'fs';
import path from 'path';
import { getRelationshipDb } from '../lib/relationshipDb';

const suggestionsPath = path.resolve(process.cwd(), '.data', 'contact_merge_suggestions.jsonl');
const threshold = parseFloat(process.env.CONF_THRESHOLD || '0.85');

function main() {
  if (!fs.existsSync(suggestionsPath)) {
    console.log('No suggestions file found:', suggestionsPath);
    return;
  }
  const db = getRelationshipDb();
  const lines = fs.readFileSync(suggestionsPath, 'utf8').split('\n').filter(Boolean);
  let applied = 0;
  for (const line of lines) {
    try {
      const s = JSON.parse(line);
      const conf = Number(s.confidence || 0);
      if (!s.handle || !s.canonical || conf < threshold) continue;
      const stmt = db.prepare(`
        UPDATE contacts
        SET canonical_handle = ?, confidence = ?
        WHERE handle = ?
      `);
      const res = stmt.run(s.canonical, conf, s.handle);
      if (res.changes > 0) applied++;
    } catch (_e) {
      // skip bad lines
    }
  }
  console.log(`Applied ${applied} merges at threshold >= ${threshold}`);
}

main();
